# Generated by Django 5.2.9 on 2026-10-05 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rythu_mitra', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ph_num', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('acres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_season', models.CharField(blank=True, max_length=50, null=True)),
                ('farming_stage', models.CharField(max_length=100)),
                ('cultivation_date', models.DateField()),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('title_te', models.CharField(blank=True, max_length=255)),
                ('message_te', models.TextField(blank=True)),
                ('notification_type', models.CharField(default='spraying', max_length=50)),
                ('spray_date', models.DateField(blank=True, null=True)),
                ('days_remaining', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rythu_mitra.cropregistration')),
            ],
        ),
    ]
